rgb_camera:
  color_profile: '640x480x15'
  profile: '640x480x15' # For backwards compatibility
color_qos: "SYSTEM_DEFAULT"

depth_module:
  depth_profile: '640x480x15'
  infra_profile: '640x480x15'
  profile: '640x480x15' # For backwards compatibility
  emitter_enabled: 0
  emitter_on_off: false
depth_qos: "SYSTEM_DEFAULT"
depth_info_qos: "SYSTEM_DEFAULT"

enable_infra1: false
enable_infra2: false

align_depth:
  enable: true
